Web/Wantoeat.Web/Controllers/FavoritesController.cs
namespace Wantoeat.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    using Microsoft.AspNetCore.Mvc;

    using Wantoeat.Services.Data;

    [Authorize]
    public class FavoritesController : BaseController
    {
        private readonly IFavoritesService favoritesService;

        public FavoritesController(IFavoritesService favoritesService)
        {
            this.favoritesService = favoritesService;
        }

        public async Task<IActionResult> All()
        {
            var favouriteRecipes = this.favoritesService.GetAllFavouritesByUserName(this.User.Identity.Name).ToList();

            return View(favouriteRecipes);
        }

        public async Task<IActionResult> Add(int id)
        {
            var result = this.favoritesService.Add(id, this.User.Identity.Name);

            if (result == false)
            {
                throw new ArgumentNullException();
            }

            return RedirectToAction(nameof(All));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var result = await this.favoritesService.DeleteAsync(id, this.User.Identity.Name);

            if (result == false)
            {
                throw new NullReferenceException();
            }

            return RedirectToAction(nameof(All));
        }
    }
}

Web/Wantoeat.Web/Controllers/HomeController.cs
namespace Wantoeat.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Wantoeat.Services.Data;
    using Wantoeat.Services.Mapping;
    using Wantoeat.Web.ViewModels.Allergens;
    using Wantoeat.Web.ViewModels.Ingredients;
    using Wantoeat.Web.ViewModels.Recipes;
    using Wantoeat.Web.ViewModels.Search;

    public class HomeController : BaseController
    {
        private readonly IRecipeService recipeService;
        private readonly IIngredientService ingredientService;
        private readonly IAllergensService allergensService;

        public HomeController(IRecipeService recipeService, IIngredientService ingredientService, IAllergensService allergensService)
        {
            this.recipeService = recipeService;
            this.ingredientService = ingredientService;
            this.allergensService = allergensService;
        }

        public async Task<IActionResult> Index()
        {
                var recipes = await this.recipeService.GetAllToViewModel<RecipeSimpleViewModel>().ToListAsync();

                return this.View(recipes);
        }

        public async Task<IActionResult> SearchByIngredients(int[] selected)
        {
            if (selected.Length > 0)
            {
                var matchedRecipes = await this.recipeService.GetRecipesByMatchingIngredients(selected).To<RecipeSimpleViewModel>().ToListAsync();

                var searchedIngredients = await this.ingredientService.GetAllToViewModelByIds<RecipeCreateIngredientViewModel>(selected).ToListAsync();

                var recipesViewModel = new RecipeAllViewModel { Recipes = matchedRecipes, Ingredients = searchedIngredients };

                return this.View("SearchResult", recipesViewModel);
            }

            var ingredients = this.ingredientService.GetAllToViewModel<IngredientSearchViewModel>().ToArray();

            SearchByIngredientsInputModel viewModel = new SearchByIngredientsInputModel { Ingredients = ingredients };

            return this.View(viewModel);
        }

        public async Task<IActionResult> SearchByAllergens(int[] selected)
        {
            if (selected.Length > 0)
            {
                var matchedRecipes = this.recipeService.GetAllNonContainingByAllergenId(selected);
                var blq = matchedRecipes.To<RecipeSimpleViewModel>().AsEnumerable();

                var searchedAllergens = await this.allergensService.GetAllToViewModelByIds<AllergenSimpleViewModel>(selected).ToListAsync();

                var recipesViewModel = new RecipeAllViewModel { Recipes = blq, Allergens = searchedAllergens };

                return this.View("SearchResult", recipesViewModel);
            }

            var allergens = this.allergensService.GetAllToViewModel<AllergenSimpleViewModel>().ToList();

            return this.View(allergens);
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() => this.View();
    }
}

Web/Wantoeat.Web/Controllers/IngredientsController.cs
namespace Wantoeat.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    using Wantoeat.Services.Data;
    using Wantoeat.Web.ViewModels.Ingredients;

    public class IngredientsController : BaseController
    {
        private readonly IIngredientService ingredientService;

        public IngredientsController(IIngredientService ingredientService)
        {
            this.ingredientService = ingredientService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var viewModel = await this.ingredientService.GetViewModelByIdAsync<IngredientDetailViewModel>(id);

            if (viewModel == null)
            {
                throw new NullReferenceException();
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> All()
        {
            var ingredients = await this.ingredientService.GetAllToViewModel<IngredientSimpleViewModel>().ToListAsync();

            return this.View(ingredients);
        }
    }
}

Web/Wantoeat.Web/Controllers/RecipesController.cs
namespace Wantoeat.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    using Wantoeat.Services.Data;
    using Wantoeat.Services.Mapping;
    using Wantoeat.Web.ViewModels.Recipes;

    public class RecipesController : BaseController
    {
        private readonly IRecipeService recipesService;

        public RecipesController(IRecipeService recipeService)
        {
            this.recipesService = recipeService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var viewModel = await this.recipesService.GetViewModelByIdAsync<RecipeDetailViewModel>(id);

            if (viewModel == null)
            {
                throw new NullReferenceException();
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> All([FromQuery]string category = null)
        {
            var recipes = this.recipesService.GetByCategory(category).To<RecipeSimpleViewModel>().ToList();

            this.ViewData["category"] = category;

            return this.View(recipes);
        }
    }
}

Web/Wantoeat.Web/Views/Home/Index.cshtml
@model List<Wantoeat.Web.ViewModels.Recipes.RecipeSimpleViewModel>

@using Wantoeat.Common
@using Wantoeat.Data.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center mb-5">
    <h1 class="display-4">Do you Wantoeat?</h1>
</div>
@if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
{
<div class="row mb-5">
    <div class="col-md-3">
        <a asp-area="Administration" asp-controller="Recipes" asp-action="Create">
            <div class="row border rounded align-content-center mx-auto bg-light" style="height:150px; text-align:center">
                <h3 class="font-weight-light mx-auto">Create Recipe</h3>
            </div>
        </a>
    </div>
    <div class="col-md-3">
        <a asp-area="Administration" asp-controller="Ingredients" asp-action="Create">
            <div class="row border rounded align-content-center mx-auto bg-light" style="height:150px; text-align:center">
                <h3 class="font-weight-light mx-auto">Create Ingredient</h3>
            </div>
        </a>
    </div>
    <div class="col-md-3">
        <a asp-controller="Recipes" asp-action="All">
            <div class="row border rounded align-content-center mx-auto bg-light" style="height:150px; text-align:center">
                <h3 class="font-weight-light mx-auto">Edit recipe</h3>
            </div>
        </a>
    </div>
    <div class="col-md-3">
        <a asp-controller="Ingredients" asp-action="All">
            <div class="row border rounded align-content-center mx-auto bg-light" style="height:150px; text-align:center">
                <h3 class="font-weight-light mx-auto">Edit ingredient</h3>
            </div>
        </a>
    </div>

</div>
}
<div class="row mb-5">
    <div class="col-md-6">
        <a asp-controller="Home" asp-action="SearchByIngredients">
            <div class="row border rounded align-content-center mx-auto" style="height:150px; text-align:center">
                <h1 class="font-weight-light mx-auto">What do you have in your fridge?</h1>
            </div>
        </a>
    </div>
    <div class="col-md-6">
        <a asp-controller="Home" asp-action="SearchByAllergens">
            <div class="row border rounded align-content-center mx-auto" style="height:150px; text-align:center">
                <h1 class="font-weight-light mx-auto">What allergen are you avoiding?</h1>
            </div>
        </a>
    </div>
</div>
@if (this.SignInManager.IsSignedIn(this.User))
{
    <div class="row mb-5">
        <div class="col-md-12">
            <a asp-controller="Favorites" asp-action="All">
                <div class="row border rounded align-content-center mx-auto" style="height:150px; text-align:center">
                    <h1 class="font-weight-light mx-auto">Show me my Favorite things Toeat</h1>
                </div>
            </a>
        </div>
    </div>
}
<p>Browse our recipes:</p>
<div class="d-flex justify-content-between">
    <div id="recipes-search-bar-holder" class="form-group d-flex justify-content-between w-100">
        <input type="text" class="form-control text-primary" id="recipes-search-bar" name="search" placeholder="Search..." />
    </div>
</div>
<hr class="hr-2">
<div id="recipes" class="mt-3">
    @for (int i = 0; i < Model.Count; i += 5)
    {
        <div class="recipes-row row d-flex justify-content-around my-5">
            @for (int j = i; j < i + 5; j++)
            {
                if (j < Model.Count)
                {
                    <div class="recipe col-md-2">
                        <div class="card" style="height:100%">
                            <a asp-controller="Recipes" asp-action="Details" asp-route-id="@Model[j].Id">
                                <img class="card-img-top mx-auto d-block" style="width:155px; height:155px;" src="@Url.Content(Model[j].ImagePath)">
                                <div class="card-body">
                                    <div class="card-title text-center">@Model[j].Name</div>
                                </div>
                            </a>
                        </div>
                        <h5 class="text-primary text-center mt-3" hidden>@Model[j].Name</h5>
                    </div>
                }
                else
                {
                    <div class="recipe col-md-2 empty">
                    </div>
                }
            }
        </div>
    }
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    $('#recipes-search-bar').on("change paste keyup", function () {
        $('.recipe').show();

        let searchValue = $('#recipes-search-bar').val();

        for (let elem of $('.recipe')) {
            let recipeName = $($(elem).children()[1]).text();

            if (!recipeName.toLowerCase().includes(searchValue.toLowerCase())) {
                $(elem).hide();
            }
        }
    });
</script>

Web/Wantoeat.Web/Views/Home/SearchByAllergens.cshtml
@model List<Wantoeat.Web.ViewModels.Allergens.AllergenSimpleViewModel>

@{
    ViewData["Title"] = "SearchByallergens";
}

<!--TODO Make the button move when scrolling-->


<div class="text-center">
    <h1 class="display-4">Mark what allergy you want to escape</h1>
</div>
<form asp-action="SearchByAllergens" asp-controller="Home" method="get">
    <div class="row mt-3 mb-3">
        <div class="mx-auto">
            <input type="submit" name="allergens" class="btn btn-primary" value="Go" />
        </div>
    </div>
    <hr class="hr-2">
    <div class="row">
        @for (var i = 0; i < @Model.Count(); i++)
        {
            <div class="col-md-2">
                <div class="card mb-4">
                    <div class="card-body">
                        <img class="card-img-top" src="@Url.Content(Model[i].ImagePath)">
                        <div class="card-footer text-center bg-white" style="height:10px">
                            <div class="form-check form-check-inline">
                                <input class="form-check" type="checkbox" name="selected" value="@Model[i].Id">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</form>

Web/Wantoeat.Web/Views/Home/SearchByIngredients.cshtml
@model Wantoeat.Web.ViewModels.Search.SearchByIngredientsInputModel

@{
    ViewData["Title"] = "SearchByIngredients";
}

<!--TODO Make the button move when scrolling-->


<div>
    <h1 class="display-4">Check what want to use</h1>
</div>
<form asp-action="SearchByIngredients" asp-controller="Search" method="get">
    <div class="row mt-3 mb-3">
        <div class="mx-auto">
            <input type="submit" name="ingredientsFromUser" class="btn btn-primary" value="Go" />
        </div>
    </div>
    <div class="d-flex justify-content-between">
        <div id="recipes-search-bar-holder" class="form-group d-flex justify-content-between w-100">
            <input type="text" class="form-control text-primary" id="recipes-search-bar" name="search" placeholder="Search..." />
        </div>
    </div>
    <hr class="hr-2">
    <div id="recipes" class="mt-3">
        @for (int i = 0; i < Model.Ingredients.Count(); i += 5)
        {
            <div class="recipes-row row d-flex justify-content-around my-5">
                @for (int j = i; j < i + 5; j++)
                {
                    if (j < Model.Ingredients.Count())
                    {
                        <div class="recipe col-md-2">
                            <div class="card" style="height:100%">
                                    <img class="card-img-top" src="@Url.Content(Model.Ingredients[j].ImagePath)">
                                    <div class="card-body text-center" style="padding:0px">
                                        <div class="card-title">@Model.Ingredients[j].Name</div>
                                        <div class="card-footer ">
                                            <div class="form-check form-check-inline">
                                                <input class="form-check" type="checkbox" name="selected" value="@Model.Ingredients[j].Id">
                                            </div>
                                        </div>
                                    </div>
                            </div>
                            <h5 class="text-primary text-center mt-3" hidden>@Model.Ingredients[j].Name</h5>
                        </div>
                    }
                    else
                    {
                        <div class="recipe col-md-2 empty">
                        </div>
                    }
                }
            </div>
        }
    </div>

</form>



<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    $('#recipes-search-bar').on("change paste keyup", function () {
        $('.recipe').show();

        let searchValue = $('#recipes-search-bar').val();

        for (let elem of $('.recipe')) {
            let recipeName = $($(elem).children()[1]).text();

            if (!recipeName.toLowerCase().includes(searchValue.toLowerCase())) {
                $(elem).hide();
            }
        }
    });
</script>

Web/Wantoeat.Web/Views/Home/SearchResult.cshtml
@model Wantoeat.Web.ViewModels.Recipes.RecipeAllViewModel

@{
    this.ViewData["Title"] = "Result";
}

<div class="text-center mb-5">
    <h1 class="display-4">Your best matches are...</h1>
</div>

@{
    if (Model.Recipes.Count() == 0)
    {
        <p>There are no recipes matching your request.</p>
    }
    else
    {
        if (Model.Ingredients.Count() != 0)
        {
            <p>Your ingredients:</p>
            <ul>
                @foreach (var item in @Model.Ingredients)
                {
                    <li>@item.Name</li>
                }
            </ul>
        }
        else
        {
            <h6>
                Allergens to avoid:
                @foreach (var item in @Model.Allergens)
                {
                    <p>@item.Name</p>
                }
            </h6>
        }

    }
}

<div class="row">
    @Html.DisplayFor(x => x.Recipes)
</div>