Web/Wantoeat.Web/Areas/Administration/Controllers/RecipesController.cs
namespace Wantoeat.Web.Areas.Administration.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    using Wantoeat.Services;
    using Wantoeat.Services.Data;
    using Wantoeat.Web.ViewModels.Ingredients;
    using Wantoeat.Web.ViewModels.Recipes;

    public class RecipesController : AdministrationController
    {
        private readonly IIngredientService ingredientService;
        private readonly ICookingTimeService cookingTimeService;
        private readonly ICategoryService categoryService;
        private readonly IImageService imageService;
        private readonly IRecipeService recipeService;

        public RecipesController(IIngredientService ingredientService, ICookingTimeService cookingTimeService,
            ICategoryService categoryService, IImageService imageService, IRecipeService recipeService)
        {
            this.ingredientService = ingredientService;
            this.cookingTimeService = cookingTimeService;
            this.categoryService = categoryService;
            this.imageService = imageService;
            this.recipeService = recipeService;
        }

        public async Task<IActionResult> Create()
        {
            var cookingTimes = await this.cookingTimeService.AllToSelectListItems();
            var categories = await this.categoryService.AllToSelectListItems();

            this.ViewData["ingredients"] = await this.ingredientService.GetAllToViewModel<RecipeCreateIngredientViewModel>().ToListAsync();

            RecipeCreateInputModel model = new RecipeCreateInputModel
            {
                Categories = categories,
                CookingTimes = cookingTimes,
            };

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(RecipeCreateInputModel model)
        {
            if (!ModelState.IsValid)
            {
                var cookingTimes = await this.cookingTimeService.AllToSelectListItems();
                var categories = await this.categoryService.AllToSelectListItems();

                this.ViewData["ingredients"] = await this.ingredientService.GetAllToViewModel<RecipeCreateIngredientViewModel>().ToListAsync();

                model.Categories = categories;
                model.CookingTimes = cookingTimes;

                return this.View(model);
            }

            if (model.ImageFile != null && model.ImageFile.Length != 0)
            {
                model.ImagePath = this.imageService.UploadImage(model.ImageFile, model.Name);
            }

            var recipe = await this.recipeService.CreateAsync(model);

            if (recipe == null)
            {
                throw new NullReferenceException();
            }

            return this.RedirectToAction("Details", new { id = recipe.Id });
        }

        public async Task<IActionResult> Edit(int id)
        {
            var model = await this.recipeService.GetViewModelByIdAsync<RecipeEditInputModel>(id);

            if (model == null)
            {
                throw new NullReferenceException();
            }

            var unusedIngredients = await this.ingredientService.GetAllUnused(id).ToListAsync();

            this.ViewData["ingredients"] = unusedIngredients.Select(ingredient => new RecipeCreateIngredientViewModel
            {
                Name = ingredient.Name

            }).OrderBy(x => x.Name)
            .ToList();

            var allCookingTimes = await this.cookingTimeService.GetAll().ToListAsync();
            this.ViewData["cookingTimes"] = allCookingTimes.Select(item => item.Name).ToList();

            var allCategories = await this.categoryService.GetAll().ToListAsync();
            this.ViewData["categories"] = allCategories.Select(item => item.Name).ToList();

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RecipeEditInputModel model)
        {
            if (!ModelState.IsValid)
            {
                var unusedIngredients = await this.ingredientService.GetAllUnused(model.Id).ToListAsync();

                this.ViewData["ingredients"] = unusedIngredients.Select(ingredient => new RecipeCreateIngredientViewModel
                {
                    Name = ingredient.Name

                }).OrderBy(x => x.Name)
                .ToList();

                var allCookingTimes = await this.cookingTimeService.GetAll().ToListAsync();
                this.ViewData["cookingTimes"] = allCookingTimes.Select(item => item.Name).ToList();

                var allCategories = await this.categoryService.GetAll().ToListAsync();
                this.ViewData["categories"] = allCategories.Select(item => item.Name).ToList();

                return this.View(model);
            }

            if (model.NewImageFile != null && model.NewImageFile.Length != 0)
            {
                if (model.ImagePath != null)
                {
                    model.ImagePath = this.imageService.ReplaceImage(model.NewImageFile, model.ImagePath, model.Name);
                }
                else
                {
                    model.ImagePath = this.imageService.UploadImage(model.NewImageFile, model.Name);
                }
            }

            var recipe = await this.recipeService.EditAsync(model);

            if (recipe == null)
            {
                throw new NullReferenceException();
            }

            return this.RedirectToAction("Details", new { id = recipe.Id });
        }

        public async Task<IActionResult> Delete(int id)
        {
            var viewModel = await this.recipeService.GetViewModelByIdAsync<RecipeSimpleViewModel>(id);

            if (viewModel == null)
            {
                throw new NullReferenceException();
            }

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(RecipeSimpleViewModel viewModel)
        {
            var result = await this.recipeService.DeleteByIdAsync(viewModel.Id);

            if (result == false)
            {
                throw new NullReferenceException();
            }

            return this.RedirectToAction("All");
        }
    }
}

Web/Wantoeat.Web/Controllers/AllergensController.cs
namespace Wantoeat.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using Wantoeat.Data.Models;
    using Wantoeat.Services.Data;
    using Wantoeat.Web.ViewModels.Allergens;

    public class AllergensController : BaseController
    {
        private readonly IAllergensService allergensService;

        public AllergensController(IAllergensService allergensService)
        {
            this.allergensService = allergensService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var viewModel = await this.allergensService.GetViewModelByIdAsync<AllergenDetailViewModel>(id);

            if (viewModel == null)
            {
                // TODO: Error Handling
                return this.Redirect("/");
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> All()
        {
            var allergens = this.allergensService.GetAllToViewModel<AllergenSimpleViewModel>();

            return this.View(allergens);
        }
    }
}

Web/Wantoeat.Web/Controllers/CommentsController.cs
namespace Wantoeat.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using Wantoeat.Data.Models;
    using Wantoeat.Services.Data;
    using Wantoeat.Web.ViewModels.Comments;
    using Wantoeat.Web.ViewModels.Recipes;

    [Authorize]
    public class CommentsController : BaseController
    {
        private readonly IRecipeService recipeService;
        private readonly ICommentsService commentsService;
        private readonly UserManager<ApplicationUser> userManager;

        public CommentsController(IRecipeService recipeService, ICommentsService commentsService,
            UserManager<ApplicationUser> userManager)
        {
            this.recipeService = recipeService;
            this.commentsService = commentsService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Add(int id)
        {
            var recipe = await this.recipeService.GetViewModelByIdAsync<CommentCreateRecipeViewModel>(id);

            if (recipe == null)
            {
                throw new ArgumentNullException();
            }

            var inputModel = new CommentInputModel { Recipe = recipe, RecipeId = recipe.RecipeId};

            return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CommentInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            inputModel.UserId = this.userManager.GetUserId(this.HttpContext.User);

            var result = await this.commentsService.AddAsync(inputModel);

            if (result == false)
            {
                throw new NullReferenceException();
            }

            return this.RedirectToAction("Details", "Recipes", new { id = inputModel.RecipeId });
        }
    }
}

Web/Wantoeat.Web/Controllers/FavoritesController.cs
namespace Wantoeat.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    using Microsoft.AspNetCore.Mvc;

    using Wantoeat.Services.Data;

    [Authorize]
    public class FavoritesController : BaseController
    {
        private readonly IFavoritesService favoritesService;

        public FavoritesController(IFavoritesService favoritesService)
        {
            this.favoritesService = favoritesService;
        }

        public async Task<IActionResult> All()
        {
            var favouriteRecipes = this.favoritesService.GetAllFavouritesByUserName(this.User.Identity.Name).ToList();

            return View(favouriteRecipes);
        }

        public async Task<IActionResult> Add(int id)
        {
            var result = this.favoritesService.Add(id, this.User.Identity.Name);

            if (result == false)
            {
                throw new ArgumentNullException();
            }

            return RedirectToAction(nameof(All));
        }

        public async Task<IActionResult> Delete(int id)
        {
            var result = await this.favoritesService.DeleteAsync(id, this.User.Identity.Name);

            if (result == false)
            {
                throw new NullReferenceException();
            }

            return RedirectToAction(nameof(All));
        }
    }
}

Web/Wantoeat.Web/Controllers/IngredientsController.cs
namespace Wantoeat.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;

    using Wantoeat.Services.Data;
    using Wantoeat.Web.ViewModels.Ingredients;

    public class IngredientsController : BaseController
    {
        private readonly IIngredientService ingredientService;

        public IngredientsController(IIngredientService ingredientService)
        {
            this.ingredientService = ingredientService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var viewModel = await this.ingredientService.GetViewModelByIdAsync<IngredientDetailViewModel>(id);

            if (viewModel == null)
            {
                throw new NullReferenceException();
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> All()
        {
            var ingredients = await this.ingredientService.GetAllToViewModel<IngredientSimpleViewModel>().ToListAsync();

            return this.View(ingredients);
        }
    }
}

Web/Wantoeat.Web/Controllers/RecipesController.cs
namespace Wantoeat.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    using Wantoeat.Services.Data;
    using Wantoeat.Services.Mapping;
    using Wantoeat.Web.ViewModels.Recipes;

    public class RecipesController : BaseController
    {
        private readonly IRecipeService recipesService;

        public RecipesController(IRecipeService recipeService)
        {
            this.recipesService = recipeService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var viewModel = await this.recipesService.GetViewModelByIdAsync<RecipeDetailViewModel>(id);

            if (viewModel == null)
            {
                throw new NullReferenceException();
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> All([FromQuery]string category = null)
        {
            var recipes = this.recipesService.GetByCategory(category).To<RecipeSimpleViewModel>().ToList();

            this.ViewData["category"] = category;

            return this.View(recipes);
        }
    }
}

Web/Wantoeat.Web/Views/Recipes/All.cshtml
@model List<Wantoeat.Web.ViewModels.Recipes.RecipeSimpleViewModel>

@{
    ViewData["Title"] = "All Recipes";

    var category = new Dictionary<string, string>()
{
        { "Meat", "Meat" },
        { "Pasta", "Pasta" },
        { "Soups", "Soups" },
        { "Salads", "Salads" },
        { "Vegetarian", "Vegetarian" },
        { "Vegan", "Vegan" },
        { "Desserts", "Desserts" },
        { "Drinks", "Drinks" }
    };
}

<div class="mb-5">
    <h1 class="display-4">Look for your recipe</h1>
</div>

<div class="d-flex justify-content-between">
    <div id="recipes-search-bar-holder" class="form-group d-flex justify-content-between w-50">
        <input type="text" class="form-control text-primary" id="recipes-search-bar" name="search" placeholder="Search..." />
    </div>
    <div id="sort-holder" class="form-group w-40 d-flex justify-content-between">
        <label for="sort" class="text-right">Choose category: </label>
        <form id="order-form" action="All" method="get">
            <select id="sort" class="form-control text-primary pl-2 ml-3 w-70" name="category">
                @if (this.ViewData["category"] == null)
                {
                    <option selected>None</option>
                }
                else
                {
                    <option>None</option>
                }
                @foreach (var elem in category)
                {
                    if (elem.Key == (string)this.ViewData["category"])
                    {
                        <option value="@elem.Key" selected>@elem.Value</option>
                    }
                    else
                    {
                        <option value="@elem.Key">@elem.Value</option>
                    }
                }
            </select>
        </form>
    </div>
</div>
<hr class="hr-2">
<div id="recipes" class="mt-3">
    @for (int i = 0; i < Model.Count; i += 5)
    {
        <div class="recipes-row row d-flex justify-content-around my-5">
            @for (int j = i; j < i + 5; j++)
            {
                if (j < Model.Count)
                {
                    <div class="recipe col-md-2">
                        <div class="card" style="height:100%">
                            <a asp-controller="Recipes" asp-action="Details" asp-route-id="@Model[j].Id">
                                <img class="card-img-top" style="width:155px; height:155px;" src="@Url.Content(Model[j].ImagePath)">
                                <div class="card-body">
                                    <div class="card-title text-center">@Model[j].Name</div>
                                </div>
                            </a>
                        </div>
                        <h5 class="text-primary text-center mt-3" hidden>@Model[j].Name</h5>
                    </div>
                }
                else
                {
                    <div class="recipe col-md-2 empty">
                    </div>
                }
            }
        </div>
    }
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
        $('#sort').change(function () {
        $('#order-form').submit();
        });

    $('#recipes-search-bar').on("change paste keyup", function () {
        $('.recipe').show();

        let searchValue = $('#recipes-search-bar').val();

        for (let elem of $('.recipe')) {
            let recipeName = $($(elem).children()[1]).text();

            if (!recipeName.toLowerCase().includes(searchValue.toLowerCase())) {
                $(elem).hide();
            }
        }
    });
</script>

Web/Wantoeat.Web/Views/Recipes/Details.cshtml
@model Wantoeat.Web.ViewModels.Recipes.RecipeDetailViewModel
@using Wantoeat.Common
@using Wantoeat.Data.Models
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@{
    ViewData["Title"] = "Details";
}

<div class="row justify-content-md-center">
    <h1>@Model.Name</h1>
</div>
<hr class="hr-2">
<div class="row mt-5">
    <div class="col-md-4">
        <img src="@Url.Content(Model.ImagePath)" class="img-thumbnail">
        @if (Model.RecipeAllergens.Any())
        {
            <div class="row mt-3">
                <div class="col-md-4 text-center">
                    <h5>Allergens:</h5>
                    @foreach (var item in Model.RecipeAllergens)
                    {
                        <li class="text-left">
                            <a asp-controller="Allergens" asp-action="Details" asp-route-id="@item.Id">@item.Name</a>
                        </li>
                    }
                </div>
                <div class="col text-left">
                    <h5>Category:</h5>
                    <a asp-controller="Recipes" asp-action="All" class="text-left">@Model.CategoryName</a>
                </div>
                <div class="col text-left">
                    <h5>Cooking time:</h5>
                    <p class="text-left">@Model.CookingTimeName</p>
                </div>
            </div>
        }
    </div>
    <div class="col-md-2">
    </div>
    <div class="col-md-5">
        <div class="mb-3">
            <p class="text-justify">@Model.Description</p>
            <br />
        </div>
        <div class="row">
            <div class="col text-center">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Ingredients</th>
                            <th scope="col">Quantities</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.RecipeIngredient)
                        {
                            <tr>
                                <td align="left"><a asp-controller="Ingredients" asp-action="Details" asp-route-id="@item.IngredientId">@item.IngredientName</a></td>
                                <td align="center">@item.Quantity</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="mb-4 text-center mx-auto">
        <a asp-controller="Recipes" asp-action="All" class="btn-light btn-sm">Back to All Recipes</a>
    </div>

</div>

@if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
{
    <div class="row justify-content-md-center mt-2 mb-3">
        <div class="col-md-2 text-center">
            <a asp-area="Administration" asp-controller="Recipes" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-secondary btn-lg">Edit</a>
        </div>
        <div class="col-md-2 text-center">
            <a asp-area="Administration" asp-controller="Recipes" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-secondary btn-lg">Delete</a>
        </div>
        <div class="col-md-2 text-center">
            <a asp-area="Administration" asp-controller="Recipes" asp-action="Create" class="btn btn-secondary btn-lg">Create New</a>
        </div>
    </div>
}
@if (this.SignInManager.IsSignedIn(this.User))
{
    <div class="row justify-content-md-center mt-5">
        <div class="mb-4 text-center mx-auto">
            <a asp-controller="Comments" asp-action="Add" asp-route-id="@Model.Id" class="btn btn-secondary btn-lg">Add comment</a>
        </div>
        <div class="mb-4 text-center mx-auto">
            <a asp-controller="Favorites" asp-action="Add" asp-route-id="@Model.Id" class="btn btn-secondary btn-lg">Add to Favorites</a>
        </div>
    </div>
}
else
{
    <div class="row">
        <p class="font-weight-light mx-auto">If you would like to post a comment, please <a asp-area="Identity" asp-page="/Account/Login">login.</a></p>
    </div>
}
<div>
    <partial name="_CommentsPartial" />
</div>